version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-labDB}  # ← Используем POSTGRES_DB из .env
      POSTGRES_USER: ${DB_USER:-postgres}  # ← Используем DB_USER из .env
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres123!@}  # ← Используем DB_PASSWORD из .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SPRING_DATASOURCE_USERNAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      # Настройки приложения
      SPRING_APPLICATION_NAME: ${SPRING_APPLICATION_NAME:-labManufacture}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE_DOCKER:-docker}

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-labDB}
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-postgres123!@}

      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"

      SPRING_LIQUIBASE_CHANGE_LOG: classpath:/db/changelog/db.changelog-master.yaml
      SPRING_LIQUIBASE_ENABLED: "true"
    ports:
      - "80:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs  # для сохранения логов
    restart: unless-stopped

volumes:
  postgres_data:
