version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-labDB}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${NEXTCLOUD_DB_PASSWORD:-postgres123!@}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SPRING_DATASOURCE_USERNAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network  # ← Добавлено
    restart: unless-stopped  # ← Добавлено

  nextcloud-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${NEXTCLOUD_DB_NAME:-nextcloud}
      POSTGRES_USER: ${NEXTCLOUD_DB_USER:-nextcloud}
      POSTGRES_PASSWORD: ${NEXTCLOUD_DB_PASSWORD:-nextcloud123!@}

    volumes:
      - nextcloud_db_data:/var/lib/postgresql/data
#      - nextcloud_data:/var/www/html/data
#      - nextcloud_config:/var/www/html/config
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${NEXTCLOUD_DB_USER:-nextcloud}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    restart: unless-stopped

#  collabora:
#    container_name: collabora
#    ports:
#      - "127.0.0.1:9980:9980"  # ← Явно привязываем к localhost
#    environment:
#      - domain=localhost
#      - extra_params=--o:ssl.enable=false --o:storage.wopi.host=localhost
#    networks:
#      - app-network  # Используем общую сеть!
#    restart: unless-stopped

  app:
    build: .
    environment:
      SPRING_APPLICATION_NAME: ${SPRING_APPLICATION_NAME:-labManufacture}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE_DOCKER:-docker}

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-labDB}
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-postgres123!@}

      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"

      SPRING_LIQUIBASE_CHANGE_LOG: classpath:/db/changelog/db.changelog-master.yaml
      SPRING_LIQUIBASE_ENABLED: "true"
    ports:
      - "80:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network  # ← Добавлено
    restart: unless-stopped

  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=verysecretkey123
    networks:
      - app-network


  nextcloud:
    image: nextcloud:33-apache
    environment:
      POSTGRES_HOST: nextcloud-db
      POSTGRES_DB: ${NEXTCLOUD_DB_NAME:-nextcloud}
      POSTGRES_USER: ${NEXTCLOUD_DB_USER:-nextcloud}
      POSTGRES_PASSWORD: ${NEXTCLOUD_DB_PASSWORD:-nextcloud123!@}


      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER:-admin}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD:-admin123!@}
      NEXTCLOUD_TRUSTED_DOMAINS: |
        localhost
        127.0.0.1
        192.168.37.125
        192.168.37.125:30540
        nextcloud
        nextcloud:80
#        collabora
#        collabora:9980

      NEXTCLOUD_FILELOCKING_ENABLED: "true"
      NEXTCLOUD_FILELOCKING_TTL: "360"
      NEXTCLOUD_BACKGROUNDJOBS_MODE: "ajax"

      NEXTCLOUD_AUTOINSTALL: "false"


    ports:
      - "30540:80"
    volumes:
      - nextcloud_data:/var/www/html/data
      - nextcloud_config:/var/www/html/config
    depends_on:
      nextcloud-db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  nextcloud_db_data:  # ← Добавлен том для NextCloud DB
  nextcloud_data: # ← Объявление volume для данных Nextcloud
  nextcloud_config:  # ← Объявление volume для конфига Nextcloud
