spring.application.name=${SPRING_APPLICATION_NAME:labManufacture}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/labDB}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres123!@}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=${SPRING_LIQUIBASE_ENABLED:true}

spring.mvc.hiddenmethod.filter.enabled=true

server.port=80
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

nextcloud.username=admin
nextcloud.password=admin123!@
nextcloud.webdav-path=/remote.php/dav/files/admin/
nextcloud.shares.default-expiration-days=1000000000
nextcloud.server-url=http://nextcloud:80
nextcloud.public-url=http://192.168.37.125:30540

spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=200
spring.task.execution.pool.keep-alive=60s
spring.task.execution.thread-name-prefix=async-task-

# nextcloud.public-url=http://localhost:30540
# nextcloud.server-url=http://localhost:30540
