spring.application.name=labManufacture

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/labManufactureDB
spring.datasource.username=postgres
spring.datasource.password=Macwork

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.show_sql=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

spring.mvc.hiddenmethod.filter.enabled=true
