spring.application.name=${SPRING_APPLICATION_NAME:labManufacture}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/labManufactureDB}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Macwork}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=${SPRING_LIQUIBASE_ENABLED:true}

spring.mvc.hiddenmethod.filter.enabled=true
